package com.mobileapp.accessibility.browser;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import org.junit.Test;

/**
 * Sanity checks on the SHIPPED assets (generated by scripts/build-adult-list.js). If one of these
 * fails, fix the script or report it: never hand-edit the generated list.
 */
public class AdultAssetTest {

    private static final String ASSETS = "src/main/assets/";

    private static List<String> entries() throws Exception {
        List<String> out = new ArrayList<>();
        for (String l :
                Files.readAllLines(
                        new File(ASSETS + "adult_domains.txt").toPath(), StandardCharsets.UTF_8)) {
            if (!l.isEmpty() && !l.startsWith("#")) {
                out.add(l);
            }
        }
        return out;
    }

    private static NeverBlockList neverBlock() throws Exception {
        try (InputStream in = new FileInputStream(ASSETS + "never_block_domains.json")) {
            return NeverBlockList.load(in);
        }
    }

    @Test
    public void containsTheDomainsSeenInRecon() throws Exception {
        List<String> e = entries();
        // hanime.tv matters most: it is drawn content, where vision scored 0.007-0.067, so the
        // static list is the ONLY defence for it.
        assertTrue("pornhub.com missing", e.contains("pornhub.com"));
        assertTrue("xhamster.com missing", e.contains("xhamster.com"));
        assertTrue("hanime.tv missing", e.contains("hanime.tv"));
    }

    @Test
    public void headerRecordsTheUpstreamCommit() throws Exception {
        String text =
                new String(
                        Files.readAllBytes(new File(ASSETS + "adult_domains.txt").toPath()),
                        StandardCharsets.UTF_8);
        assertTrue(text.contains("# Upstream commit: cb5daa41eadded64f169ffe9b0cdee7000540d7f"));
        assertTrue(text.contains("# Upstream date: "));
        assertTrue(text.contains("MIT"));
    }

    @Test
    public void isAFullSizeList() throws Exception {
        assertTrue("expected ~77k domains", entries().size() > 70000);
    }

    @Test
    public void containsNoNeverBlockDomain() throws Exception {
        NeverBlockList nb = neverBlock();
        List<String> bad = new ArrayList<>();
        for (String d : entries()) {
            if (nb.covers(d)) {
                bad.add(d);
            }
        }
        assertEquals("never-block entries leaked into the list: " + bad, 0, bad.size());
    }

    @Test
    public void keepsGoogleLookalikeThatTheWildcardMustNotSwallow() throws Exception {
        // Guards the JS/Java wildcard agreement: the script must not drop this genuine adult
        // domain, and the Java list must not consider it never-block.
        assertTrue(entries().contains("google.porno.sexy"));
        assertFalse(neverBlock().covers("google.porno.sexy"));
    }

    @Test
    public void everyEntryIsAlreadyANormalisedHost() throws Exception {
        List<String> bad = new ArrayList<>();
        for (String d : entries()) {
            if (!d.equals(HostNormalizer.toHost(d))) {
                bad.add(d);
                if (bad.size() >= 10) {
                    break;
                }
            }
        }
        assertEquals("entries the normaliser would change: " + bad, 0, bad.size());
    }

    @Test
    public void neverBlockAssetHasTheAgreedEntries() throws Exception {
        NeverBlockList nb = neverBlock();
        for (String d :
                new String[] {
                    "www.google.com", "google.co.uk", "bing.com", "duckduckgo.com", "yahoo.com",
                    "www.youtube.com", "instagram.com", "facebook.com", "messenger.com",
                    "tiktok.com", "x.com", "twitter.com", "reddit.com", "snapchat.com",
                    "whatsapp.com", "en.wikipedia.org"
                }) {
            assertTrue(d + " must be never-block", nb.covers(d));
        }
    }
}
